#!/bin/bash
echo "Enter sim name: "
read dir

rm -r $dir
mkdir $dir
cp diff_mod.f90 $dir
cp input $dir
cd $dir
gfortran -Og -fimplicit-none -Wall -Wextra -fcheck=all diff_mod.f90
./a.out

#-fbounds-check -fbacktrace